### PR TITLE
add inline help for save content variable table action

### PR DESCRIPTION
**Pull request by overnin**

### CODE REVIEW

**Comment by jkage** [comment]
There is some css issue. Compare this 
reset_action_with_exceptions_2
with
save_content_variable_css_issue
The alignment of the bullet points needs some styling.

**Comment by overnin** [comment]
i don't see the bullet points with Chrome, Safari and Firefox. 
Did u clean your browser cache? if bug persists provide more details about your configuration.

**Comment by jkage** [comment]
The bug appears under "Extra Column" as seen in the diagram.

**Comment by overnin** [comment]
@jkage please review

**Comment by jkage** [comment]
The bullet points still appear, now in both Row keys and Extra column, as shown below
save_content_variable_css_issue_2

**Comment by overnin** [comment]
@jkage i add another style, in case it doesn't work, please investigate with firebug what is creating this issue cause i cannot reproduce it on my machine.

**Comment by jkage** [comment]
@overnin please review

**Pull request merged**
