### PR TITLE
export and filter user logs

### PR DESCRIPTION
**Pull request by overnin**
update ACL

### CODE REVIEW

**Comment by markphi2013** [comment]
export is not generating file it's only redirecting  to : http://localhost:4567/userLogs/exportUserLog.csv

**Comment by overnin** [comment]
I added the missing view

**Comment by markphi2013** [comment]
- [ ] In the exportUserlog file, the program column is empty/program name is not exported 
- [ ] file name "exportUserlog" is not so explicit

**Comment by overnin** [comment]
@markphi2013 for review

**Comment by markphi2013** [comment]
ok for merge

**Pull request merged**
