### PR TITLE
Chore export should be done in the backend

### PR DESCRIPTION
**Pull request by overnin**
Don't forget the backend part
https://github.com/texttochange/vusion-backend/pull/54

### CODE REVIEW

**Comment by overnin** [comment]
@jkage Fixed backend and front end, please review

**Comment by jkage** [comment]
@overnin I think when there is no program folder, we should create the folder and then do the export.

**Comment by overnin** [comment]
@jkage done, please review.

The export of unmatchableReply will be done on another pull request.

**Comment by jkage** [comment]
works well. ok for merge

**Pull request merged**
