### PR TITLE
design of add simulator participant view

### PR DESCRIPTION
**Pull request by markphi2013**
Run Aco_sync

Also move to backend 
https://github.com/texttochange/vusion-backend/pull/71

### CODE REVIEW

**Comment by overnin** [comment]
Comments:
- [ ] wording on add participant view is confusing. What is a *Normal* participant?? aren't we talking about *real participant* and *simulated participant*. So we rather have 2 tabs with those names.
- [ ] backend branch is missing to also upgrade the participant model
- [ ] change name "simulator" to "simulate participant"
- [ ] on the page simulator, the layout is different than the mockup
- [ ] on the page simulator, the message submission should be done with AJAX, and the participant profile and history should be updated on the page with regular ajax request.

**Comment by overnin** [comment]
looking good 

some comments:
- [ ] rather than creating a new function programParticipants->pullSimulateUpdate, why don't you use the programHistory->index.json?[filter to get only this participant history]
- [ ] The advantage of using the programHistory->index function is that you can use filter to only get the last messages. Indeed each history document has a timestamp, if you ask for only the history which have a timestamp > le last timestamp (one can use the timestamp of the last response). You only get the new ones. For the first request, this condition can be omitted as you are initialising the simulator view. 
- [ ] on the html view, we are missing some button to navigate to the participant view or participant edit page.
- [ ] each message time is ISO... which is not easy to read. i would suggest more human friendly display like "1min ago", "12h ago" but this is a bit tricky as you need to regularly update all the message in the page. To help you with this task, there is a javascript library already in Vusion named moment.js. It can take a date in ISO format and transform it to be displayed in a human friendly way.
- [ ] the simulator html box should display a scroll bar so that the user knows if there are messages below
- [ ] the input box should take "pressing enter key" as submit
- [ ] when a new message appear at the bottom, the submit box is automatically scrolled down in an instant at each pull from the server. can you find a more user friendly way? if new message appear (and only if) the user should be notified visually that a message appeared down.
- [ ] the profile information are not updated on the left. Please use the programParticipant->view.json to get those information.
- [ ] there is a bar at the bottom of the html page... why?
screen shot 2015-08-05 at 16 29 06
- [ ] the box border of the simulate view is back. It's a bit too strong. In our UI we try to avoir black as it has strong effect. I would rather use some gray color for this border.
- [ ] on the profile box, the participant opt-in/optout status should be displayed.

**Comment by overnin** [comment]
- [ ] issue on the participant index, for participant of previous version number, the field ```simulated``` is not defined. To fix by handling the case in the view.
screen shot 2015-08-20 at 17 14 29

**Comment by overnin** [comment]
Still to be agreed:
1. the ```ttc-simulator.js``` relies on 2 element ids ```ttc-simulator-output``` and ```simulator-profile```, should those element be created in the .js file rather than in the view ```simulator_mo.ctp```
2. a trigger to reload the data from the server should take place when the user is sending a text should this be done via a reference ```('#ttc-simulator-output').update()``` call or an event call. The event might be more JS.

**Comment by overnin** [comment]
- [ ] when sending a MO and submitting with enter key, the page is reloading. Instead it should have the same behaviour as clicking on the ```send``` button.

**Comment by markphi2013** [comment]
@overnin : i need some help with the two task in the list above 
- [ ] when the sending MO form is submitted, it should automatically trigger the ajax request to update participant history and details

- [ ] show enrolled field in participant's details
       I have manged to get the enrolled dialogue id but not the name which is required

**Comment by markphi2013** [comment]
@overnin  
Enrolled should show the Dialogue Name not the ID

screenshot from 2015-09-04 14 52 23

**Comment by overnin** [comment]
Still do to @markphi2013 on the UX of the the creation of the simulated participant:
- [ ] when creating a simulated participant, the user should be redirected to the simulated page of this participant
- [ ] when creating simulated participant, there is not need of tagging them ```simulated``` or ```opt-in``
- [ ] when creating an simulated from optin message => needs to add an extra field with which message the user wants to perform it.
- [ ] for the add participant page, the tab style should be changed to the one used in mash import branch https://github.com/texttochange/vusion-frontend/pull/263

**Comment by markphi2013** [comment]
- [ ] Before merging with develop check basic.css the remove any duplicating classes on tabs

**Comment by overnin** [comment]
- [ ] fix simulate button on real participant view page
screen shot 2015-09-09 at 16 07 57
- [ ] on add simulated participant add information text about adding with message might fail if the corresponding request doesn't exist.
- [ ] can we have the message input only to appear if the 'optin keyword' is selected

**Comment by overnin** [comment]
ok for merge \o/

**Pull request closed without merging**
