### PR TITLE
Feature/content variable save action

### PR DESCRIPTION
**Pull request by overnin**
Don't forget the backend part. https://github.com/texttochange/vusion-backend/pull/68

Note that the action summary is missing when folding the action save-content-variable-table on the UI. Doesn't prevent from testing.

### CODE REVIEW

**Comment by markphi2013** [comment]
screenshot from 2015-05-20 08 52 18

Fail

**Comment by overnin** [comment]
@markphi2013 missing file added

**Comment by markphi2013** [comment]
When i create a new program in vusion and add a new table, the save content var table Action is not working 

Below is what i see in the program logs
screenshot from 2015-05-22 12 02 51

**Comment by markphi2013** [comment]
On edit the Header Row Keys change to have the same value
screenshot from 2015-05-22 16 32 22

**Comment by overnin** [comment]
is it because the 2 first row headers are *ID*, so it's rather a validation to be done on the *content variable table*. Could you confirm @markphi2013 ?

**Comment by overnin** [comment]
@jkage could you please test the feature.

**Comment by overnin** [comment]
Need to
- [ ] remove empty row
- [ ] add the folded action summary

**Comment by jkage** [comment]
@overnin same report as mark. The first 2 row headers are DATE and ID. However, <i>on edit</i> of a request, the row header keys are always changed to the last key in the table. 
As shown in mark's comment.

**Comment by overnin** [comment]
@jkage please review

**Comment by jkage** [comment]
ok for merge

**Pull request merged**
