### PR TITLE
Feature/report issue improve

### PR DESCRIPTION
**Pull request by markphi2013**

### CODE REVIEW

**Comment by jkage** [comment]
@markphi2013 the user reporting the issue gets an email, but vusion-issues does not receive the email. Can you check and see wht the problem is?

**Comment by markphi2013** [comment]
ok

**Comment by jkage** [comment]
ok mark

**Comment by overnin** [comment]
This is my comment

**Comment by markphi2013** [comment]
From the testing we have done vusion user can only send an email to [vusion-issue] mailing list   only and only if the user has an email ending with <b> "@ttcmobile.com or @texttochange.com"</b>
Thus 
I would request @JoukeJ  to look at this 

thanks

**Comment by jkage** [comment]
ok for merge

**Pull request closed without merging**
