### PR TITLE
logging runactions event into the userlog

### PR DESCRIPTION
**Pull request by markphi2013**

### CODE REVIEW

**Comment by overnin** [comment]
- [ ] unit test in missing
- [ ] naming of the ```initUserEvent($actionEventData)``` is not that good, ```setEventData($eventData)``` is much more clear

**Comment by markphi2013** [comment]
@overnin  please review when you get time

**Comment by markphi2013** [comment]
Ok 
- ```$this->eventData```   is used to define the eventdata in the protected function _saveUserAction

- ```$actionEventData```  hold  action the value defined from the controller function which in this case is the phone number 

- ```setUserEventData(```  this is a public function define in any controller on an Action to set the variable user prefers to use in the logging

**Comment by overnin** [comment]
- [ ] remove the Session component from the UserLogMonitorComponent

**Comment by overnin** [comment]
Ok for merge

**Pull request closed without merging**
