### PR TITLE
Hotfix/1.6.11

### PR DESCRIPTION
**Pull request by overnin**
The backend user should have the permission to write in the program's folder.

TO SMOCK TEST

### CODE REVIEW

**Comment by markphi2013** [comment]
In the Export index the delete action is no longer showing

**Comment by markphi2013** [comment]
Also Incase of a failure i think the Download bottom should be remove or not show in the export index page

**Comment by overnin** [comment]
Did you run the aco_sync and the initDB?

Which user level are you testing with?

**Comment by overnin** [comment]
Ok for removing the download button.

**Comment by markphi2013** [comment]
ok true after i run aco_sync the delete shows

**Comment by markphi2013** [comment]
Ok for merge

**Pull request merged**
