### PR TITLE
Feature/reset action with exceptions

### PR DESCRIPTION
**Pull request by jkage**
Make sure to review the backend too here https://github.com/texttochange/vusion-backend/pull/66

### CODE REVIEW

**Comment by jkage** [comment]
@overnin please review

**Comment by jkage** [comment]
@overnin please review

**Comment by markphi2013** [comment]
I think Helper would be nice if added on the label to show users how to add list on tags and labels

**Comment by jkage** [comment]
@markphi2013 please review

**Comment by markphi2013** [comment]
Keep Tags is a feature that enables participants to keep some of the tags they originally had as the reset action takes place.
Tags should be written in a comma separated list like<i> tag1, tag2...</i>
<b>Leave this field blank if you do not wish to retain any tags</b>


Remove the spaces btn lines

**Comment by markphi2013** [comment]
ok for merge

**Pull request merged**
