### PR TITLE
enroll participant on import

### PR DESCRIPTION
**Pull request by markphi2013**

### CODE REVIEW

**Comment by overnin** [comment]
Wouldn't it be more flexible to have a mass enrol button rather than a enrol at import? Mass enrol button would allow to also enrol after the participant is imported.

**Comment by markphi2013** [comment]
@overnin  hello i don't seem to have any failing tests due to undefined function parameter. please confirm

**Comment by overnin** [comment]
Still a test is failing
screen shot 2015-08-31 at 17 11 41

**Comment by overnin** [comment]
ok for merge

**Pull request closed without merging**
