### PR TITLE
Feature/participant invite participant

### PR DESCRIPTION
**Pull request by markphi2013**

### CODE REVIEW

**Comment by markphi2013** [comment]
@overnin  i have added the doc for Sms invite action : http://vusion-doc.texttochange.org/en/advanced/sms_inviting.html
pliz review it also when u get time

**Comment by overnin** [comment]
About the doc http://vusion-doc.texttochange.org/en/advanced/sms_inviting.html
- [ ] the title of the page ```SMS inviting``` is different for ```SMS invite action```,  please be consistent, i personally thing that ```SMS invite action``` is the best.
- [ ] more a UI comment but the sceenshot made me think about it, the help inline is missing on the content field

**Comment by overnin** [comment]
Neither in the inline help or the vusion doc is a mention that the inviting participant has to send ```invite <phone>```. What is missing:
- [ ] for the user, he needs to tick the box ```in case no matching...```
- [ ] for the inviting participant, he needs a feedback message if the phone is absent

Another point regarding the phone input of the invitee, we need to clearly explain what should be the format ie ```+25611111```.

**Comment by markphi2013** [comment]
backend code changes  for empty phone number
https://github.com/texttochange/vusion-backend/pull/57

**Comment by overnin** [comment]
- [ ] layout issue for the online help, strange empty lines before the bullet points, could you remove it.
screen shot 2015-03-10 at 12 25 13 pm

**Pull request closed without merging**
