### PR TITLE
made vusion footer static

### PR DESCRIPTION
**Pull request by markphi2013**

### CODE REVIEW

**Comment by jkage** [comment]
I prefer the old footer layout better. 
Also the two scroll bars Jouke needed to remove are still there (on chrome).
Perhaps some clarification from Jouke is needed.

**Comment by overnin** [comment]
Working well @markphi2013, could you apply this design (removing table tag) on
1) the program header
2) the page content (between the nav menu and the page content)

**Comment by markphi2013** [comment]
- [ ] Request
     - [ ] add 
     - [ ] edit
     - [ ] Index
- [ ] Dialogue
     - [ ] add 
     - [ ] edit
     - [ ] Index
- [ ] Separate Messages
     - [ ] add 
     - [ ] edit
     - [ ] Index
- [ ] Predefined Messages
     - [ ] add 
     - [ ] edit
     - [ ] Index
- [ ] Content Variables
     - [ ] add 
     - [ ] edit
     - [ ] Index
- [ ] Participants
     - [ ] add 
     - [ ] edit
     - [ ] Index
     - [ ] View
- [ ] History
     - [ ] add 
     - [ ] edit
     - [ ] Index
- [ ] Settings
     - [ ] add 
     - [ ] edit
     - [ ] Index
     - [ ] View
- [ ] Logs
     - [ ] Index
- [ ] Program List

**Comment by markphi2013** [comment]
To do list two
- [ ] Users                                                        
     - [ ] New User 
     - [ ] edit
     - [ ] View
     - [ ] Index
     - [ ] Invite User
- [ ] Groups
     - [ ] New group 
     - [ ] edit
     - [ ] Index
     - [ ] View
- [ ] Short codes
     - [ ] New  
     - [ ] edit
     - [ ] Index
- [ ] Templates
     - [ ] New  
     - [ ] edit
     - [ ] Index
- [ ] User Logs
     - [ ] Index

**Comment by markphi2013** [comment]
An empty space is left 

On folding the filter 
screenshot from 2015-05-20 13 06 00

On closing the filter 
screenshot from 2015-05-20 13 07 16

**Comment by overnin** [comment]
Mark do not forget to fix the fixed header-content for admin pages
screen shot 2015-05-20 at 21 31 29

**Comment by overnin** [comment]
@markphi2013 Please dry the following

```css
.fix-program-header {
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 999;
    height: 50px;   
    background: #19C1FF;
    left: 0;
    right: 20;
}

.fix-content-header {
    position: fixed;
    top: 50px;
    z-index: 998;
    left: 240px;
    right: 20px;
    background: white;
    border-bottom: 1px lightgrey solid;
    padding-top: 8px;
}

.users-index .fix-content-header {
    position: fixed;
    top: -1px;
    z-index: 998;
    left: 254px;
    right: 20px;
    background: white;
    border-bottom: 1px lightgrey solid;
    padding-top: 8px;
}

.shortcode-index .fix-content-header {
    position: fixed;
    top: -1px;
    z-index: 998;
    left: 242px;
    right: 20px;
    background: white;
    border-bottom: 1px lightgrey solid;
    padding-top: 8px;
}
```

**Comment by markphi2013** [comment]
Clear up looks Good i think Okay for Merge 

\0/

**Comment by markphi2013** [comment]
Ooooooh No the Userlogs index  is needs a fix 
screenshot from 2015-05-22 15 13 06

**Comment by markphi2013** [comment]
looks Good i think Okay for Merge  \0/


What do you think? @overnin

**Comment by overnin** [comment]
let's merge!

**Comment by overnin** [comment]
@jkage please review asap

**Comment by jkage** [comment]
ok for merge

**Pull request merged**
