### PR TITLE
Feature/upgrade javascript to use requireJS

### PR DESCRIPTION
**Pull request by jkage**

### CODE REVIEW

**Comment by overnin** [comment]
@markphi2013 ready for review, please try to check that the javascript is properly working on ALL the views.

**Comment by overnin** [comment]
@markphi2013 to which extend are the 2 layout used?
- default2.ctp
- popup.ctp

**Comment by markphi2013** [comment]
On  add request 

screenshot from 2015-10-06 17 06 08

**Comment by markphi2013** [comment]
Report issues pop up is fails 

screenshot from 2015-10-08 14 00 50

**Comment by markphi2013** [comment]
Program stats not loading on program index 


screenshot from 2015-10-12 12 54 16

**Comment by markphi2013** [comment]
Ok for merge

**Pull request merged**
